### ISSUE TITLE
При компиляции выдает ошибку

### ISSUE THREAD

**Issue by AlexAndryF** [afiskon/pwm-ppm-decode#1]
Здравствуйте!
При компиляции скетча вылазит ошибка. В чем может быть дело? Не подскажете?

Arduino: 1.8.7 (Windows 7), Плата:"Arduino Nano, ATmega328P (Old Bootloader)"

C:\Program Files\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files\Arduino\hardware -hardware C:\Users\ALBERT\AppData\Local\Arduino15\packages -tools C:\Program Files\Arduino\tools-builder -tools C:\Program Files\Arduino\hardware\tools\avr -tools C:\Users\ALBERT\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files\Arduino\libraries -libraries C:\Users\ALBERT\Documents\Arduino\libraries -fqbn=arduino:avr:nano:cpu=atmega328old -ide-version=10807 -build-path C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486 -warnings=none -build-cache C:\Users\ALBERT\AppData\Local\Temp\arduino_cache_962369 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude-6.3.0-arduino14.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.avr-gcc.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.avr-gcc-5.4.0-atmel3.6.1-arduino2.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.arduinoOTA.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.arduinoOTA-1.2.1.path=C:\Program Files\Arduino\hardware\tools\avr -verbose C:\Users\ALBERT\Documents\Arduino\sketch_aug01c\sketch_aug01c.ino
C:\Program Files\Arduino\arduino-builder -compile -logger=machine -hardware C:\Program Files\Arduino\hardware -hardware C:\Users\ALBERT\AppData\Local\Arduino15\packages -tools C:\Program Files\Arduino\tools-builder -tools C:\Program Files\Arduino\hardware\tools\avr -tools C:\Users\ALBERT\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files\Arduino\libraries -libraries C:\Users\ALBERT\Documents\Arduino\libraries -fqbn=arduino:avr:nano:cpu=atmega328old -ide-version=10807 -build-path C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486 -warnings=none -build-cache C:\Users\ALBERT\AppData\Local\Temp\arduino_cache_962369 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude-6.3.0-arduino14.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.avr-gcc.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.avr-gcc-5.4.0-atmel3.6.1-arduino2.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.arduinoOTA.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.arduinoOTA-1.2.1.path=C:\Program Files\Arduino\hardware\tools\avr -verbose C:\Users\ALBERT\Documents\Arduino\sketch_aug01c\sketch_aug01c.ino
Using board 'nano' from platform in folder: C:\Program Files\Arduino\hardware\arduino\avr
Using core 'arduino' from platform in folder: C:\Program Files\Arduino\hardware\arduino\avr
Detecting libraries used...
"C:\\Program Files\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10807 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Program Files\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "C:\\Users\\ALBERT\\AppData\\Local\\Temp\\arduino_build_724486\\sketch\\sketch_aug01c.ino.cpp" -o nul
"C:\\Program Files\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10807 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Program Files\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Users\\ALBERT\\Documents\\Arduino\\libraries\\pwm-ppm-decode-master" "C:\\Users\\ALBERT\\AppData\\Local\\Temp\\arduino_build_724486\\sketch\\sketch_aug01c.ino.cpp" -o nul
Using cached library dependencies for file: C:\Users\ALBERT\Documents\Arduino\libraries\pwm-ppm-decode-master\main.cpp
Generating function prototypes...
"C:\\Program Files\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10807 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Program Files\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Users\\ALBERT\\Documents\\Arduino\\libraries\\pwm-ppm-decode-master" "C:\\Users\\ALBERT\\AppData\\Local\\Temp\\arduino_build_724486\\sketch\\sketch_aug01c.ino.cpp" -o "C:\\Users\\ALBERT\\AppData\\Local\\Temp\\arduino_build_724486\\preproc\\ctags_target_for_gcc_minus_e.cpp"
"C:\\Program Files\\Arduino\\tools-builder\\ctags\\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\\Users\\ALBERT\\AppData\\Local\\Temp\\arduino_build_724486\\preproc\\ctags_target_for_gcc_minus_e.cpp"
Компиляция скетча...
"C:\\Program Files\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10807 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Program Files\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Users\\ALBERT\\Documents\\Arduino\\libraries\\pwm-ppm-decode-master" "C:\\Users\\ALBERT\\AppData\\Local\\Temp\\arduino_build_724486\\sketch\\sketch_aug01c.ino.cpp" -o "C:\\Users\\ALBERT\\AppData\\Local\\Temp\\arduino_build_724486\\sketch\\sketch_aug01c.ino.cpp.o"
Compiling libraries...
Compiling library "pwm-ppm-decode-master"
Используем предварительно скомпилированный файл: C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\libraries\pwm-ppm-decode-master\main.cpp.o
Compiling core...
Using precompiled core: C:\Users\ALBERT\AppData\Local\Temp\arduino_cache_962369\core\core_arduino_avr_nano_cpu_atmega328old_5638c217b04eda8279099c4937887265.a
Linking everything together...
"C:\\Program Files\\Arduino\\hardware\\tools\\avr/bin/avr-gcc" -w -Os -g -flto -fuse-linker-plugin -Wl,--gc-sections -mmcu=atmega328p -o "C:\\Users\\ALBERT\\AppData\\Local\\Temp\\arduino_build_724486/sketch_aug01c.ino.elf" "C:\\Users\\ALBERT\\AppData\\Local\\Temp\\arduino_build_724486\\sketch\\sketch_aug01c.ino.cpp.o" "C:\\Users\\ALBERT\\AppData\\Local\\Temp\\arduino_build_724486\\libraries\\pwm-ppm-decode-master\\main.cpp.o" "C:\\Users\\ALBERT\\AppData\\Local\\Temp\\arduino_build_724486/..\\arduino_cache_962369\\core\\core_arduino_avr_nano_cpu_atmega328old_5638c217b04eda8279099c4937887265.a" "-LC:\\Users\\ALBERT\\AppData\\Local\\Temp\\arduino_build_724486" -lm
C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\libraries\pwm-ppm-decode-master\main.cpp.o (symbol from plugin): In function `rising()':

(.text+0x0): multiple definition of `rising()'

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\sketch\sketch_aug01c.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\libraries\pwm-ppm-decode-master\main.cpp.o (symbol from plugin): In function `rising()':

(.text+0x0): multiple definition of `curr_channel'

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\sketch\sketch_aug01c.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\libraries\pwm-ppm-decode-master\main.cpp.o (symbol from plugin): In function `rising()':

(.text+0x0): multiple definition of `prev_time'

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\sketch\sketch_aug01c.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\libraries\pwm-ppm-decode-master\main.cpp.o (symbol from plugin): In function `rising()':

(.text+0x0): multiple definition of `pwm_value'

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\sketch\sketch_aug01c.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\libraries\pwm-ppm-decode-master\main.cpp.o (symbol from plugin): In function `rising()':

(.text+0x0): multiple definition of `overflow'

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\sketch\sketch_aug01c.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\libraries\pwm-ppm-decode-master\main.cpp.o (symbol from plugin): In function `rising()':

(.text+0x0): multiple definition of `portB'

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\sketch\sketch_aug01c.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\libraries\pwm-ppm-decode-master\main.cpp.o (symbol from plugin): In function `rising()':

(.text+0x0): multiple definition of `portC'

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\sketch\sketch_aug01c.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\libraries\pwm-ppm-decode-master\main.cpp.o (symbol from plugin): In function `rising()':

(.text+0x0): multiple definition of `portD'

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\sketch\sketch_aug01c.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\libraries\pwm-ppm-decode-master\main.cpp.o (symbol from plugin): In function `rising()':

(.text+0x0): multiple definition of `PCintPort::enable(PCintPort::PCintPin*, void (*)(), unsigned char)'

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\sketch\sketch_aug01c.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\libraries\pwm-ppm-decode-master\main.cpp.o (symbol from plugin): In function `rising()':

(.text+0x0): multiple definition of `PCintPort::addPin(unsigned char, void (*)(), unsigned char)'

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\sketch\sketch_aug01c.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\libraries\pwm-ppm-decode-master\main.cpp.o (symbol from plugin): In function `rising()':

(.text+0x0): multiple definition of `PCintPort::attachInterrupt(unsigned char, void (*)(), int)'

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\sketch\sketch_aug01c.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\libraries\pwm-ppm-decode-master\main.cpp.o (symbol from plugin): In function `rising()':

(.text+0x0): multiple definition of `PCintPort::detachInterrupt(unsigned char)'

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\sketch\sketch_aug01c.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\libraries\pwm-ppm-decode-master\main.cpp.o (symbol from plugin): In function `rising()':

(.text+0x0): multiple definition of `PCintPort::PCint()'

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\sketch\sketch_aug01c.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\libraries\pwm-ppm-decode-master\main.cpp.o (symbol from plugin): In function `rising()':

(.text+0x0): multiple definition of `PCintPort::curr'

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\sketch\sketch_aug01c.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\libraries\pwm-ppm-decode-master\main.cpp.o (symbol from plugin): In function `rising()':

(.text+0x0): multiple definition of `PCintPort::pinState'

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\sketch\sketch_aug01c.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\libraries\pwm-ppm-decode-master\main.cpp.o (symbol from plugin): In function `rising()':

(.text+0x0): multiple definition of `PCintPort::arduinoPin'

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\sketch\sketch_aug01c.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\libraries\pwm-ppm-decode-master\main.cpp.o (symbol from plugin): In function `rising()':

(.text+0x0): multiple definition of `__vector_3'

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\sketch\sketch_aug01c.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\libraries\pwm-ppm-decode-master\main.cpp.o (symbol from plugin): In function `rising()':

(.text+0x0): multiple definition of `__vector_4'

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\sketch\sketch_aug01c.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\libraries\pwm-ppm-decode-master\main.cpp.o (symbol from plugin): In function `rising()':

(.text+0x0): multiple definition of `__vector_5'

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\sketch\sketch_aug01c.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\libraries\pwm-ppm-decode-master\main.cpp.o (symbol from plugin): In function `rising()':

(.text+0x0): multiple definition of `setup'

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\sketch\sketch_aug01c.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\libraries\pwm-ppm-decode-master\main.cpp.o (symbol from plugin): In function `rising()':

(.text+0x0): multiple definition of `loop'

C:\Users\ALBERT\AppData\Local\Temp\arduino_build_724486\sketch\sketch_aug01c.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

collect2.exe: error: ld returned 1 exit status

Используем библиотеку pwm-ppm-decode-master в папке: C:\Users\ALBERT\Documents\Arduino\libraries\pwm-ppm-decode-master (legacy)
exit status 1
Ошибка компиляции для платы Arduino Nano.

**Comment by afiskon** [comment]
Приведенный код не является скетчем для Arduino IDE. Это самостоятельный проект со своим Makefile.
